# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMwithFour' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMwithFour
  pod 'SDWebImage'

  target 'MVVMwithFourTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMwithFourUITests' do
    # Pods for testing
  end

end
